name: '`PR Copilot'
description: 'Review your PR by the OpenAI'
author: 'mackowski'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  git_diff:
    description: 'Diff from GIT'
    required: true
    default: 'invalid input'

# Define your outputs here.
outputs:
  result:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
