name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action PR Copilot - ehh
        id: test-action
        uses: ./
        with:
          git_diff: '
            diff --git a/.github/workflows/getdiff.yml
            b/.github/workflows/getdiff.yml index 15969ab..5efbf8c 100644 ---
            a/.github/workflows/getdiff.yml +++ b/.github/workflows/getdiff.yml
            @@ -20,3 +20,31 @@ jobs: - name: use diff run: | echo $DIFF
            +  store-diff: +      runs-on: ubuntu-latest +      name: Get Diff
            and store in diff.txt +      steps: +       - name: Checkout
            +         id: checkout_2 +         uses: actions/checkout@v4
            +         with: +            fetch-depth: 2 +       - name: git diff
            to file +         run: git diff ${{
            github.event.pull_request.base.sha }}..${{
            github.event.pull_request.head.sha }} > diff.txt +       - name:
            Upload math result for job 1 +         uses:
            actions/upload-artifact@v4 +         with: +           name: diff
            +           path: diff.txt +  use-diff: +    runs-on: ubuntu-latest
            +    needs: store-diff +    name: use diff +    steps: +    - name:
            Download diff from store-diff +      uses:
            actions/download-artifact@v4 +      with: +        name: diff +    -
            shell: bash +      run: cat ./diff.txt'
          openAiApiKey: ${{ secrets.OPENAIAPIKEY }}

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.result }}"
