name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action PR Copilot
        id: test-action
        uses: ./
        with:
          git_diff: "DIFF=diff --git a/README.md b/README.md index dec2cbe..364645a 100644 --- a/README.md +++ b/README.md @@ -1,2 +1,3 @@ test -test +test change this line +add this line"

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.result }}"
